services:
  h5ai:
    build: .
    container_name: h5ai
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
      ADMINIP: 127.0.0.1
      TRUSTSN: 192.168.0.0/16
      DNSADDR: "8.8.8.8 8.8.4.4"
    ports:
      - "8080:80/tcp"
    volumes:
      - /mnt/containers/h5ai:/mnt/config
      - /mnt/containers/public:/mnt/media
